@echo off
echo Starting Backend Server...
start cmd /k "cd backend && npm install && npm start"

echo Starting Frontend Server...
start cmd /k "cd frontend && npm install && npm run dev"

echo Both servers are starting...
